package io.github.fvrodas.jaml.ui.common.themes

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import io.github.fvrodas.jaml.R

sealed class JamlColorScheme(val lightColorScheme: ColorScheme, val darkColorScheme: ColorScheme) {

    data object Default : JamlColorScheme(
        lightColorScheme = ColorScheme(
            primary = Color(0xff777777),
            onPrimary = Color(0xffe6e6e6),
            primaryContainer = Color(0xffe6e6e6),
            onPrimaryContainer = Color(0xff424242),
            inversePrimary = Color(0xFF000000),
            secondary = Color(0xff424242),
            onSecondary = Color(0xffe6e6e6),
            secondaryContainer = Color(0xff424242),
            onSecondaryContainer = Color(0xffe6e6e6),
            tertiary = Color(0xff424242),
            onTertiary = Color(0xffe6e6e6),
            tertiaryContainer = Color(0xff424242),
            onTertiaryContainer = Color(0xffe6e6e6),
            background = Color(0xffe6e6e6),
            onBackground = Color(0xff424242),
            surface = Color(0xffe6e6e6),
            onSurface = Color(0xff424242),
            surfaceVariant = Color(0xffe6e6e6),
            onSurfaceVariant = Color(0xff424242),
            surfaceTint = Color(0xffe6e6e6),
            inverseSurface = Color(0xFF000000),
            inverseOnSurface = Color(0xFF000000),
            error = Color(0xffe6e6e6),
            onError = Color(0xff424242),
            errorContainer = Color(0xffe6e6e6),
            onErrorContainer = Color(0xff424242),
            outline = Color(0xff424242),
            outlineVariant = Color(0xff424242),
            scrim = Color(0xff424242),
        ),
        darkColorScheme = ColorScheme(
            primary = Color(0xff888888),
            onPrimary = Color(0xffffffff),
            primaryContainer = Color(0xff424242),
            onPrimaryContainer = Color(0xffe6e6e6),
            inversePrimary = Color(0xFF000000),
            secondary = Color(0xffe6e6e6),
            onSecondary = Color(0xff424242),
            secondaryContainer = Color(0xffe6e6e6),
            onSecondaryContainer = Color(0xffe6e6e6),
            tertiary = Color(0xffe6e6e6),
            onTertiary = Color(0xffe6e6e6),
            tertiaryContainer = Color(0xffe6e6e6),
            onTertiaryContainer = Color(0xffe6e6e6),
            background = Color(0xff424242),
            onBackground = Color(0xffe6e6e6),
            surface = Color(0xff424242),
            onSurface = Color(0xffe6e6e6),
            surfaceVariant = Color(0xff424242),
            onSurfaceVariant = Color(0xffe6e6e6),
            surfaceTint = Color(0xff424242),
            inverseSurface = Color(0xff424242),
            inverseOnSurface = Color(0xffe6e6e6),
            error = Color(0xff424242),
            onError = Color(0xffe6e6e6),
            errorContainer = Color(0xff424242),
            onErrorContainer = Color(0xffe6e6e6),
            outline = Color(0xffe6e6e6),
            outlineVariant = Color(0xffe6e6e6),
            scrim = Color(0xff424242),
        )
    )

    data object Gruvbox : JamlColorScheme(
        lightColorScheme = ColorScheme(
            primary = Color(0xff689d6a),
            onPrimary = Color(0xff3c3836),
            primaryContainer = Color(0xff689d6a),
            onPrimaryContainer = Color(0xff3c3836),
            inversePrimary = Color(0xffb16286),
            secondary = Color(0xff458588),
            onSecondary = Color(0xff3c3836),
            secondaryContainer = Color(0xff458588),
            onSecondaryContainer = Color(0xff3c3836),
            tertiary = Color(0xff424242),
            onTertiary = Color(0xff3c3836),
            tertiaryContainer = Color(0xff98971a),
            onTertiaryContainer = Color(0xff3c3836),
            background = Color(0xfffbf1c7),
            onBackground = Color(0xff3c3836),
            surface = Color(0xfffbf1c7),
            onSurface = Color(0xff3c3836),
            surfaceVariant = Color(0xffebdbb2),
            onSurfaceVariant = Color(0xff3c3836),
            surfaceTint = Color(0xffebdbb2),
            inverseSurface = Color(0xff282828),
            inverseOnSurface = Color(0xfffbf1c7),
            error = Color(0xffcc241d),
            onError = Color(0xff3c3836),
            errorContainer = Color(0xffcc241d),
            onErrorContainer = Color(0xff3c3836),
            outline = Color(0xff689d6a),
            outlineVariant = Color(0xff458588),
            scrim = Color(0xff3c3836),
        ),
        darkColorScheme = ColorScheme(
            primary = Color(0xff689d6a),
            onPrimary = Color(0xffebdbb2),
            primaryContainer = Color(0xff689d6a),
            onPrimaryContainer = Color(0xffebdbb2),
            inversePrimary = Color(0xffb16286),
            secondary = Color(0xff458588),
            onSecondary = Color(0xffebdbb2),
            secondaryContainer = Color(0xff458588),
            onSecondaryContainer = Color(0xffebdbb2),
            tertiary = Color(0xff98971a),
            onTertiary = Color(0xffebdbb2),
            tertiaryContainer = Color(0xff98971a),
            onTertiaryContainer = Color(0xffebdbb2),
            background = Color(0xff282828),
            onBackground = Color(0xffebdbb2),
            surface = Color(0xff282828),
            onSurface = Color(0xffebdbb2),
            surfaceVariant = Color(0xff3c3836),
            onSurfaceVariant = Color(0xffebdbb2),
            surfaceTint = Color(0xff282828),
            inverseSurface = Color(0xffebdbb2),
            inverseOnSurface = Color(0xff3c3836),
            error = Color(0xffcc241d),
            onError = Color(0xffebdbb2),
            errorContainer = Color(0xffcc241d),
            onErrorContainer = Color(0xffebdbb2),
            outline = Color(0xff689d6a),
            outlineVariant = Color(0xff458588),
            scrim = Color(0xff3c3836),
        )
    )
}

val themesByName = mapOf(
    R.string.theme_default to JamlColorScheme.Default,
    R.string.theme_gruvbox to JamlColorScheme.Gruvbox
)

