package io.github.fvrodas.jaml.ui.common.themes

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.github.fvrodas.jaml.R
import io.github.fvrodas.jaml.ui.common.settings.LauncherTheme

@Suppress("MagicNumber")
sealed class JamlColorScheme(val lightColorScheme: ColorScheme, val darkColorScheme: ColorScheme) {

    data object Default : JamlColorScheme(
        lightColorScheme = lightColorScheme(
            primary = primaryLight,
            onPrimary = onPrimaryLight,
            primaryContainer = primaryContainerLight,
            onPrimaryContainer = onPrimaryContainerLight,
            secondary = secondaryLight,
            onSecondary = onSecondaryLight,
            secondaryContainer = secondaryContainerLight,
            onSecondaryContainer = onSecondaryContainerLight,
            tertiary = tertiaryLight,
            onTertiary = onTertiaryLight,
            tertiaryContainer = tertiaryContainerLight,
            onTertiaryContainer = onTertiaryContainerLight,
            error = errorLight,
            onError = onErrorLight,
            errorContainer = errorContainerLight,
            onErrorContainer = onErrorContainerLight,
            background = backgroundLight,
            onBackground = onBackgroundLight,
            surface = surfaceLight,
            onSurface = onSurfaceLight,
            surfaceVariant = surfaceVariantLight,
            onSurfaceVariant = onSurfaceVariantLight,
            outline = outlineLight,
            outlineVariant = outlineVariantLight,
            scrim = scrimLight,
            inverseSurface = inverseSurfaceLight,
            inverseOnSurface = inverseOnSurfaceLight,
            inversePrimary = inversePrimaryLight,
            surfaceDim = surfaceDimLight,
            surfaceBright = surfaceBrightLight,
            surfaceContainerLowest = surfaceContainerLowestLight,
            surfaceContainerLow = surfaceContainerLowLight,
            surfaceContainer = surfaceContainerLight,
            surfaceContainerHigh = surfaceContainerHighLight,
            surfaceContainerHighest = surfaceContainerHighestLight,
        ),
        darkColorScheme = darkColorScheme(
            primary = primaryDark,
            onPrimary = onPrimaryDark,
            primaryContainer = primaryContainerDark,
            onPrimaryContainer = onPrimaryContainerDark,
            secondary = secondaryDark,
            onSecondary = onSecondaryDark,
            secondaryContainer = secondaryContainerDark,
            onSecondaryContainer = onSecondaryContainerDark,
            tertiary = tertiaryDark,
            onTertiary = onTertiaryDark,
            tertiaryContainer = tertiaryContainerDark,
            onTertiaryContainer = onTertiaryContainerDark,
            error = errorDark,
            onError = onErrorDark,
            errorContainer = errorContainerDark,
            onErrorContainer = onErrorContainerDark,
            background = backgroundDark,
            onBackground = onBackgroundDark,
            surface = surfaceDark,
            onSurface = onSurfaceDark,
            surfaceVariant = surfaceVariantDark,
            onSurfaceVariant = onSurfaceVariantDark,
            outline = outlineDark,
            outlineVariant = outlineVariantDark,
            scrim = scrimDark,
            inverseSurface = inverseSurfaceDark,
            inverseOnSurface = inverseOnSurfaceDark,
            inversePrimary = inversePrimaryDark,
            surfaceDim = surfaceDimDark,
            surfaceBright = surfaceBrightDark,
            surfaceContainerLowest = surfaceContainerLowestDark,
            surfaceContainerLow = surfaceContainerLowDark,
            surfaceContainer = surfaceContainerDark,
            surfaceContainerHigh = surfaceContainerHighDark,
            surfaceContainerHighest = surfaceContainerHighestDark,
        )
    )

    data object Gruvbox : JamlColorScheme(
        lightColorScheme = lightColorScheme(
            primary = Color(0xff689d6a),
            onPrimary = Color(0xff3c3836),
            primaryContainer = Color(0xff689d6a),
            onPrimaryContainer = Color(0xff3c3836),
            inversePrimary = Color(0xffb16286),
            secondary = Color(0xff458588),
            onSecondary = Color(0xff3c3836),
            secondaryContainer = Color(0xff458588),
            onSecondaryContainer = Color(0xff3c3836),
            tertiary = Color(0xff424242),
            onTertiary = Color(0xff3c3836),
            tertiaryContainer = Color(0xff98971a),
            onTertiaryContainer = Color(0xff3c3836),
            background = Color(0xfffbf1c7),
            onBackground = Color(0xff3c3836),
            surface = Color(0xfffbf1c7),
            onSurface = Color(0xff3c3836),
            surfaceVariant = Color(0xffebdbb2),
            onSurfaceVariant = Color(0xff3c3836),
            surfaceTint = Color(0xffebdbb2),
            inverseSurface = Color(0xff282828),
            inverseOnSurface = Color(0xfffbf1c7),
            error = Color(0xffcc241d),
            onError = Color(0xff3c3836),
            errorContainer = Color(0xffcc241d),
            onErrorContainer = Color(0xff3c3836),
            outline = Color(0xff689d6a),
            outlineVariant = Color(0xff458588),
            scrim = Color(0xff3c3836),
            surfaceBright = Color(0xffd5c4a1),
            surfaceDim = Color(0xffd5c4a1),
            surfaceContainer = Color(0xffd5c4a1),
            surfaceContainerHigh = Color(0xffd5c4a1),
            surfaceContainerHighest = Color(0xffd5c4a1),
            surfaceContainerLow = Color(0xffd5c4a1),
            surfaceContainerLowest = Color(0xffd5c4a1),
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xff689d6a),
            onPrimary = Color(0xffebdbb2),
            primaryContainer = Color(0xff689d6a),
            onPrimaryContainer = Color(0xffebdbb2),
            inversePrimary = Color(0xffb16286),
            secondary = Color(0xff458588),
            onSecondary = Color(0xffebdbb2),
            secondaryContainer = Color(0xff458588),
            onSecondaryContainer = Color(0xffebdbb2),
            tertiary = Color(0xff98971a),
            onTertiary = Color(0xffebdbb2),
            tertiaryContainer = Color(0xff98971a),
            onTertiaryContainer = Color(0xffebdbb2),
            background = Color(0xff282828),
            onBackground = Color(0xffebdbb2),
            surface = Color(0xff282828),
            onSurface = Color(0xffebdbb2),
            surfaceVariant = Color(0xff3c3836),
            onSurfaceVariant = Color(0xffebdbb2),
            surfaceTint = Color(0xff282828),
            inverseSurface = Color(0xffebdbb2),
            inverseOnSurface = Color(0xff3c3836),
            error = Color(0xffcc241d),
            onError = Color(0xffebdbb2),
            errorContainer = Color(0xffcc241d),
            onErrorContainer = Color(0xffebdbb2),
            outline = Color(0xff689d6a),
            outlineVariant = Color(0xff458588),
            scrim = Color(0xff3c3836),
            surfaceBright = Color(0xff1d2021),
            surfaceDim = Color(0xff1d2021),
            surfaceContainer = Color(0xff1d2021),
            surfaceContainerHigh = Color(0xff1d2021),
            surfaceContainerHighest = Color(0xff1d2021),
            surfaceContainerLow = Color(0xff1d2021),
            surfaceContainerLowest = Color(0xff1d2021),
        )
    )

    data object Nord : JamlColorScheme(
        lightColorScheme = lightColorScheme(
            primary = Color(0xff5e81ac),
            onPrimary = Color(0xffeceff4),
            primaryContainer = Color(0xff81a1c1),
            onPrimaryContainer = Color(0xff2e3440),
            inversePrimary = Color(0xff88c0d0),
            secondary = Color(0xff81a1c1),
            onSecondary = Color(0xffeceff4),
            secondaryContainer = Color(0xffd8dee9),
            onSecondaryContainer = Color(0xff2e3440),
            tertiary = Color(0xffa3be8c),
            onTertiary = Color(0xffeceff4),
            tertiaryContainer = Color(0xffebcb8b),
            onTertiaryContainer = Color(0xff2e3440),
            background = Color(0xffeceff4),
            onBackground = Color(0xff2e3440),
            surface = Color(0xffeceff4),
            onSurface = Color(0xff2e3440),
            surfaceVariant = Color(0xffe5e9f0),
            onSurfaceVariant = Color(0xff3b4252),
            surfaceTint = Color(0xff5e81ac),
            inverseSurface = Color(0xff2e3440),
            inverseOnSurface = Color(0xffeceff4),
            error = Color(0xffbf616a),
            onError = Color(0xffeceff4),
            errorContainer = Color(0xffd08770),
            onErrorContainer = Color(0xff2e3440),
            outline = Color(0xff4c566a),
            outlineVariant = Color(0xff434c5e),
            scrim = Color(0xff2e3440),
            surfaceBright = Color(0xffeceff4),
            surfaceDim = Color(0xffd8dee9),
            surfaceContainer = Color(0xffe5e9f0),
            surfaceContainerHigh = Color(0xffe5e9f0),
            surfaceContainerHighest = Color(0xffe5e9f0),
            surfaceContainerLow = Color(0xffeceff4),
            surfaceContainerLowest = Color(0xffffffff),
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xff88c0d0),
            onPrimary = Color(0xff2e3440),
            primaryContainer = Color(0xff5e81ac),
            onPrimaryContainer = Color(0xffeceff4),
            inversePrimary = Color(0xff5e81ac),
            secondary = Color(0xff81a1c1),
            onSecondary = Color(0xff2e3440),
            secondaryContainer = Color(0xff4c566a),
            onSecondaryContainer = Color(0xffeceff4),
            tertiary = Color(0xff8fbcbb),
            onTertiary = Color(0xff2e3440),
            tertiaryContainer = Color(0xffa3be8c),
            onTertiaryContainer = Color(0xff2e3440),
            background = Color(0xff2e3440),
            onBackground = Color(0xffeceff4),
            surface = Color(0xff2e3440),
            onSurface = Color(0xffeceff4),
            surfaceVariant = Color(0xff3b4252),
            onSurfaceVariant = Color(0xffd8dee9),
            surfaceTint = Color(0xff88c0d0),
            inverseSurface = Color(0xffeceff4),
            inverseOnSurface = Color(0xff2e3440),
            error = Color(0xffbf616a),
            onError = Color(0xff2e3440),
            errorContainer = Color(0xffd08770),
            onErrorContainer = Color(0xff2e3440),
            outline = Color(0xffd8dee9),
            outlineVariant = Color(0xff4c566a),
            scrim = Color(0xff000000),
            surfaceBright = Color(0xff434c5e),
            surfaceDim = Color(0xff3b4252),
            surfaceContainer = Color(0xff3b4252),
            surfaceContainerHigh = Color(0xff434c5e),
            surfaceContainerHighest = Color(0xff4c566a),
            surfaceContainerLow = Color(0xff3b4252),
            surfaceContainerLowest = Color(0xff2e3440),
        )
    )
}

val colorSchemeByName = mapOf(
    R.string.colorscheme_default to JamlColorScheme.Default,
    R.string.colorscheme_gruvbox to JamlColorScheme.Gruvbox,
    R.string.colorscheme_nord to JamlColorScheme.Nord
)

val launcherThemeByName = mapOf(
    R.string.theme_light to LauncherTheme.Light,
    R.string.theme_dark to LauncherTheme.Dark,
    R.string.theme_system to LauncherTheme.System
)
