package io.github.fvrodas.jaml.ui.common.themes

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.github.fvrodas.jaml.R

sealed class JamlColorScheme(val lightColorScheme: ColorScheme, val darkColorScheme: ColorScheme) {

    data object Default : JamlColorScheme(
        lightColorScheme = lightColorScheme(
            primary = primaryLight,
            onPrimary = onPrimaryLight,
            primaryContainer = primaryContainerLight,
            onPrimaryContainer = onPrimaryContainerLight,
            secondary = secondaryLight,
            onSecondary = onSecondaryLight,
            secondaryContainer = secondaryContainerLight,
            onSecondaryContainer = onSecondaryContainerLight,
            tertiary = tertiaryLight,
            onTertiary = onTertiaryLight,
            tertiaryContainer = tertiaryContainerLight,
            onTertiaryContainer = onTertiaryContainerLight,
            error = errorLight,
            onError = onErrorLight,
            errorContainer = errorContainerLight,
            onErrorContainer = onErrorContainerLight,
            background = backgroundLight,
            onBackground = onBackgroundLight,
            surface = surfaceLight,
            onSurface = onSurfaceLight,
            surfaceVariant = surfaceVariantLight,
            onSurfaceVariant = onSurfaceVariantLight,
            outline = outlineLight,
            outlineVariant = outlineVariantLight,
            scrim = scrimLight,
            inverseSurface = inverseSurfaceLight,
            inverseOnSurface = inverseOnSurfaceLight,
            inversePrimary = inversePrimaryLight,
            surfaceDim = surfaceDimLight,
            surfaceBright = surfaceBrightLight,
            surfaceContainerLowest = surfaceContainerLowestLight,
            surfaceContainerLow = surfaceContainerLowLight,
            surfaceContainer = surfaceContainerLight,
            surfaceContainerHigh = surfaceContainerHighLight,
            surfaceContainerHighest = surfaceContainerHighestLight,
        ),
        darkColorScheme = darkColorScheme(
            primary = primaryDark,
            onPrimary = onPrimaryDark,
            primaryContainer = primaryContainerDark,
            onPrimaryContainer = onPrimaryContainerDark,
            secondary = secondaryDark,
            onSecondary = onSecondaryDark,
            secondaryContainer = secondaryContainerDark,
            onSecondaryContainer = onSecondaryContainerDark,
            tertiary = tertiaryDark,
            onTertiary = onTertiaryDark,
            tertiaryContainer = tertiaryContainerDark,
            onTertiaryContainer = onTertiaryContainerDark,
            error = errorDark,
            onError = onErrorDark,
            errorContainer = errorContainerDark,
            onErrorContainer = onErrorContainerDark,
            background = backgroundDark,
            onBackground = onBackgroundDark,
            surface = surfaceDark,
            onSurface = onSurfaceDark,
            surfaceVariant = surfaceVariantDark,
            onSurfaceVariant = onSurfaceVariantDark,
            outline = outlineDark,
            outlineVariant = outlineVariantDark,
            scrim = scrimDark,
            inverseSurface = inverseSurfaceDark,
            inverseOnSurface = inverseOnSurfaceDark,
            inversePrimary = inversePrimaryDark,
            surfaceDim = surfaceDimDark,
            surfaceBright = surfaceBrightDark,
            surfaceContainerLowest = surfaceContainerLowestDark,
            surfaceContainerLow = surfaceContainerLowDark,
            surfaceContainer = surfaceContainerDark,
            surfaceContainerHigh = surfaceContainerHighDark,
            surfaceContainerHighest = surfaceContainerHighestDark,
        )
    )

    data object Gruvbox : JamlColorScheme(
        lightColorScheme = lightColorScheme(
            primary = Color(0xff689d6a),
            onPrimary = Color(0xff3c3836),
            primaryContainer = Color(0xff689d6a),
            onPrimaryContainer = Color(0xff3c3836),
            inversePrimary = Color(0xffb16286),
            secondary = Color(0xff458588),
            onSecondary = Color(0xff3c3836),
            secondaryContainer = Color(0xff458588),
            onSecondaryContainer = Color(0xff3c3836),
            tertiary = Color(0xff424242),
            onTertiary = Color(0xff3c3836),
            tertiaryContainer = Color(0xff98971a),
            onTertiaryContainer = Color(0xff3c3836),
            background = Color(0xfffbf1c7),
            onBackground = Color(0xff3c3836),
            surface = Color(0xfffbf1c7),
            onSurface = Color(0xff3c3836),
            surfaceVariant = Color(0xffebdbb2),
            onSurfaceVariant = Color(0xff3c3836),
            surfaceTint = Color(0xffebdbb2),
            inverseSurface = Color(0xff282828),
            inverseOnSurface = Color(0xfffbf1c7),
            error = Color(0xffcc241d),
            onError = Color(0xff3c3836),
            errorContainer = Color(0xffcc241d),
            onErrorContainer = Color(0xff3c3836),
            outline = Color(0xff689d6a),
            outlineVariant = Color(0xff458588),
            scrim = Color(0xff3c3836),
            surfaceBright = Color(0xffd5c4a1),
            surfaceDim = Color(0xffd5c4a1),
            surfaceContainer = Color(0xffd5c4a1),
            surfaceContainerHigh = Color(0xffd5c4a1),
            surfaceContainerHighest = Color(0xffd5c4a1),
            surfaceContainerLow = Color(0xffd5c4a1),
            surfaceContainerLowest = Color(0xffd5c4a1),
        ),
        darkColorScheme = darkColorScheme(
            primary = Color(0xff689d6a),
            onPrimary = Color(0xffebdbb2),
            primaryContainer = Color(0xff689d6a),
            onPrimaryContainer = Color(0xffebdbb2),
            inversePrimary = Color(0xffb16286),
            secondary = Color(0xff458588),
            onSecondary = Color(0xffebdbb2),
            secondaryContainer = Color(0xff458588),
            onSecondaryContainer = Color(0xffebdbb2),
            tertiary = Color(0xff98971a),
            onTertiary = Color(0xffebdbb2),
            tertiaryContainer = Color(0xff98971a),
            onTertiaryContainer = Color(0xffebdbb2),
            background = Color(0xff282828),
            onBackground = Color(0xffebdbb2),
            surface = Color(0xff282828),
            onSurface = Color(0xffebdbb2),
            surfaceVariant = Color(0xff3c3836),
            onSurfaceVariant = Color(0xffebdbb2),
            surfaceTint = Color(0xff282828),
            inverseSurface = Color(0xffebdbb2),
            inverseOnSurface = Color(0xff3c3836),
            error = Color(0xffcc241d),
            onError = Color(0xffebdbb2),
            errorContainer = Color(0xffcc241d),
            onErrorContainer = Color(0xffebdbb2),
            outline = Color(0xff689d6a),
            outlineVariant = Color(0xff458588),
            scrim = Color(0xff3c3836),
            surfaceBright = Color(0xff1d2021),
            surfaceDim = Color(0xff1d2021),
            surfaceContainer = Color(0xff1d2021),
            surfaceContainerHigh = Color(0xff1d2021),
            surfaceContainerHighest = Color(0xff1d2021),
            surfaceContainerLow = Color(0xff1d2021),
            surfaceContainerLowest = Color(0xff1d2021),
        )
    )
}

val colorSchemeByName = mapOf(
    R.string.colorscheme_default to JamlColorScheme.Default,
    R.string.colorscheme_gruvbox to JamlColorScheme.Gruvbox
)

val launcherThemeByName = mapOf(
    R.string.theme_light to LauncherTheme.Light,
    R.string.theme_dark to LauncherTheme.Dark,
    R.string.theme_system to LauncherTheme.System
)
